### ISSUE TITLE
Booking wizard is not showing available days

### ISSUE THREAD

**Issue by romalytvynenko** [RebelCode/eddbk-wizard#1]
API returns sessions but wizard is not showing that days are having some sessions.

**Comment by romalytvynenko** [comment]
Fixed in:
https://github.com/RebelCode/eddbk-wizard/commit/093ff0001f7c716052a44176ebe92c8e121f6394

**Comment by markzahra** [comment]
The booking wizard step 2 is not showing the available dates and times as set up in the Service's availability calendar.

On my test site, no matter what service I select in step 1, step 2 shows the dates of August 1, 2, 3 and 6, and September 3, 4, 5 and 6 as available. These are not dates set as availabilities on any of my services.
